-- 코드를 입력하세요
SELECT CAR_TYPE, COUNT(*) AS CARS FROM CAR_RENTAL_COMPANY_CAR
WHERE OPTIONS LIKE '%통풍%' OR OPTIONS LIKE '%열선%' OR OPTIONS LIKE '%가죽%'
GROUP BY CAR_TYPE
ORDER BY CAR_TYPE ASC

구분해야 할 옵션이 여러 개일 때 LIKE를 쓸 때는 위의 쿼리처럼 하나하나 LIKE를 다 써줘야 한다.
  
SELECT CAR_TYPE, COUNT(*) AS CARS FROM CAR_RENTAL_COMPANY_CAR
WHERE OPTIONS REGEXP '통풍시트|열선시트|가죽시트'
GROUP BY CAR_TYPE
ORDER BY CAR_TYPE ASC

REGEXP를 쓰면 위의 쿼리처럼 더 깔끔해진다.
