-- 코드를 입력하세요
SELECT I.INGREDIENT_TYPE, SUM(F.TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF F
JOIN ICECREAM_INFO I ON F.FLAVOR = I.FLAVOR
GROUP BY I.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER ASC

총 주문량을 구할 땐 COUNT가 아니라 SUM이다.
성분 별로 분류해야하기 때문에 GROUP BY로 I.INGREDIENT_TYPE를 써서
성분 별로 분류 해야 한다.
