-- 코드를 입력하세요
SELECT TRUNCATE(PRICE / 10000, 0) * 10000 AS PRICE_GROUP, COUNT(*) AS PRODUCTS
FROM PRODUCT
GROUP BY PRICE_GROUP
ORDER BY PRICE_GROUP ASC

TRUNCATE 쿼리 : 지정한 숫자의 자릿수까지 모두 버리는 쿼리

SELECT TRUNCATE(PRICE, -4) AS PRICE_GROUP, COUNT(*) AS PRODUCTS
FROM PRODUCT
GROUP BY PRICE_GROUP
ORDER BY PRICE_GROUP ASC

이렇게도 쓸 수 있다.
